config/routes.rb
# typed: ignore
# frozen_string_literal: true

Ektar::Engine.routes.draw do
  root to: "select_organization#new"

  resource :sessions, path: I18n.t("routes.session"), only: [:new, :create, :destroy]
  resources :registrations, path: I18n.t("routes.registration"), only: [:new, :create]
  resources :select_organization, path: I18n.t("routes.select_organization"), only: [:new, :create, :update]

  get I18n.t("routes.reset_password"), to: "reset_passwords#new", as: :new_reset_password
  post I18n.t("routes.reset_password"), to: "reset_passwords#create", as: :reset_password

  get I18n.t("routes.password"), to: "passwords#edit", as: :edit_passwords
  patch I18n.t("routes.password"), to: "passwords#update", as: :passwords

  get I18n.t("routes.registration"), to: "registrations#new", as: :new_registrations
  get I18n.t("routes.accept_invitation"), to: "accept_invitations#new", as: :new_accept_invitations
  patch I18n.t("routes.accept_invitation"), to: "accept_invitations#update", as: :accept_invitations

  namespace :super_admin do
    root to: "super_admin/organizations#index"

    resources :organizations, path: I18n.t("routes.organizations"), only: [:index, :show, :destroy]
    resources :plans, path: I18n.t("routes.plans"), except: [:show]
    resources :users, path: I18n.t("routes.users"), except: [:edit, :update]
  end

  namespace :admin, path: Ektar.configuration.admin_path do
    resources :users, path: I18n.t("routes.users"), only: [:new, :index, :destroy]
    resources :invitations, path: I18n.t("routes.invitations"), only: [:new, :create]
    resources :select_plan, only: [:new, :create]
  end
end

app/models/ektar/user.rb
# typed: ignore
# frozen_string_literal: true

module Ektar
  class User < ApplicationRecord
    include PgSearch::Model

    has_secure_password :password, validations: true

    has_many :memberships, class_name: "Ektar::Membership", foreign_key: :ektar_user_id, inverse_of: :user, autosave: true
    has_many :organizations, class_name: "Ektar::Organization", through: :memberships, source: :organization, autosave: true
    has_many :used_passwords, class_name: "Ektar::UsedPassword", foreign_key: :ektar_user_id

    validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}, uniqueness: {case_sensitive: false}
    validates :password, format: {with: /(?=.*\d)(?=.*[a-z])(?=.*[A-Z])/}, unless: proc { |user| user.password.blank? }
    validates :memberships, presence: true, if: ->(user) { !user.super_admin }
    validate :validate_unique_password, if: ->(user) { user.password_digest_changed? }

    accepts_nested_attributes_for :memberships, limit: 1, reject_if: :reject_empty_organization!

    after_create :store_password
    before_update :store_password, if: :password_digest_changed?

    scope :super_admins, -> { where(super_admin: true) }

    pg_search_scope :search_full, against: :email,
                                  using: {tsearch: {prefix: true, any_word: true}}

    sig { returns(String) }
    def to_param
      global_id
    end

    sig { returns(T::Boolean) }
    def blocked?
      blocked_at?
    end

    sig { params(organization: Ektar::Organization).returns(T::Boolean) }
    def is_member?(organization)
      organizations.include?(organization)
    end

    sig { returns(T::Boolean) }
    def admin?
      !admin_of.size.zero?
    end

    sig { params(organization: T.nilable(Ektar::Organization)).returns(T::Boolean) }
    def is_admin?(organization)
      admin_of.detect { |membership| membership.ektar_organization_id == organization.id }.present?
    end

    sig { returns(T::Array[Ektar::Membership]) }
    def admin_of
      @memberships_admin ||= memberships.select { |membership| membership.role == "admin" }
    end

    sig { returns(T.nilable(Ektar::Membership)) }
    def membership
      memberships.first
    end

    private

    sig { returns(Ektar::UsedPassword) }
    def store_password
      if used_passwords.count == Ektar.configuration.password_retain_count
        UsedPassword.destroy_by(id: used_passwords.order(created_at: :asc).pluck(:id).first)
      end
      used_passwords.create(password_digest: password_digest)
    end

    sig { params(attributes: T::Hash[T.any(String, Symbol), T.any(String, T::Hash[String, String])]).returns(T::Boolean) }
    def reject_empty_organization!(attributes)
      attributes.dig(:organization_attributes, :name).blank?
    end

    sig { void }
    def validate_unique_password
      used_passwords.each do |used_password|
        bcrypt = ::BCrypt::Password.new(used_password.password_digest)
        hashed_value = ::BCrypt::Engine.hash_secret(password, bcrypt.salt)

        errors.add(:password, :password_already_used) if hashed_value == used_password.password_digest
      end
    end
  end
end

app/controllers/ektar/admin/users_controller.rb
# typed: ignore
# frozen_string_literal: true

module Ektar
  module Admin
    class UsersController < ApplicationController
      before_action :organization_has_plan, only: [:index]

      resourceful(list_attributes: %i[email updated_at last_activity_at blocked_at],
                  form_attributes: {email: :input, password: :password, password_confirmation: :password},
                  show_attributes: %i[id email updated_at],
                  find_by: :global_id,
                  only: [:new, :index, :destroy],
                  policy_class: Ektar::UserPolicy,
                  resource_class: Ektar::User)

      sig { void }
      def index
        index! do |scope|
          if current_user.super_admin?
            scope.where(super_admin: true)
          else
            scope.includes(:memberships)
              .where(ektar_memberships: {ektar_organization_id: current_organization})
              .order(created_at: :desc)
          end
        end
      end

      sig { void }
      def destroy
        object = Ektar::User.find_by!(find_by_param => params[:id])
        object.membership&.update blocked_at: Time.zone.now

        set_flash(errors: object.errors, klass: resource_class.model_name.element, active: action_name)

        redirect_to collection_path
      end

      private

      sig { returns(String) }
      def collection_path
        ektar.admin_users_path
      end

      sig { params(resource: ActiveRecord::Base).returns(String) }
      def resource_path(resource)
        ektar.admin_user_path(resource)
      end

      sig { params(resource: ActiveRecord::Base).returns(String) }
      def edit_resource_path(resource)
        ektar.edit_admin_user_path(resource)
      end

      sig { returns(ActionController::Parameters) }
      def secure_params
        params.require(:user).permit(T.must(form_attributes).keys, memberships_attributes: [{organization_attributes: [:name]}])
      end

      sig { void }
      def organization_has_plan
        return if current_organization&.plan_present?

        redirect_to ektar.new_admin_select_plan_path
      end
    end
  end
end

app/controllers/ektar/super_admin/users_controller.rb
# typed: ignore
# frozen_string_literal: true

module Ektar
  module SuperAdmin
    class UsersController < ApplicationController
      extend T::Sig
      include Pagy::Backend

      resourceful(list_attributes: %i[email updated_at last_activity_at blocked_at],
                  form_attributes: {email: :input, password: :password, password_confirmation: :password},
                  show_attributes: %i[id email updated_at],
                  find_by: :global_id,
                  except: [:edit, :update],
                  namespace: :super_admin,
                  resource_class: Ektar::User,
                  policy_class: Ektar::UserPolicy)

      sig { void }
      def index
        index! { |scope| scope.where(super_admin: true) }
      end

      sig { void }
      def destroy
        object = Ektar::User.find_by!(find_by_param => params[:id])
        object&.update blocked_at: Time.zone.now

        set_flash(errors: object.errors, klass: resource_class.model_name.element, active: action_name)

        redirect_to collection_path
      end

      private

      sig { params(resource: T.untyped).returns(T::Boolean) }
      def allow_delete?(resource)
        !resource.blocked? && resource.id != current_user.id
      end

      sig { returns(Symbol) }
      def link_attribute
        :email
      end

      sig { returns(String) }
      def new_resource_path
        ektar.registrations_path
      end

      sig { returns(ActionController::Parameters) }
      def secure_params
        params.require(:user).permit(T.must(form_attributes).keys, memberships_attributes: [{organization_attributes: [:name]}])
      end
    end
  end
end

app/helpers/ektar/user_helper.rb
# typed: strong
module Ektar
  module UserHelper
  end
end

app/views/ektar/admin/users/_resource.html.erb
<tr data-id="<%= resource.id %>">
  <% list_attributes.each do |attribute| %>
    <% value = resource[attribute] %>
    <td class="<%= value.is_a?(String) ? "has-text-left" : "has-text-right" %>">
      <% if attribute == link_attribute %>
        <%= link_to attribute_value(value), resource_path(resource) %>
      <% else %>
        <% if attribute == :blocked_at %>
          <%= attribute_value(resource.memberships.first.blocked_at) %>
        <% else %>
          <%= attribute_value(value || resource.send(attribute)) %>
        <% end %>
      <% end %>
    </td>
  <% end %>

  <%= render partial: "actions", locals: { resource: resource } %>
</tr>

app/views/ektar/admin/users/_tools.html.erb
<nav class="level">
  <div class="level-left">
    <div class="level-item">
      <h2 class="title is-4"><%= model_human_name(resource_class) %><h2>
    </div>

    <div class="level-item">
      <%= form_with(url: collection_path, method: :get, local: true) do |form| %>
        <div class="field has-addons">
          <div class="control">
            <%= text_field_tag :q, params[:q], class: "input", maxlength: 40, placeholder: t("form.placeholders.search") %>
          </div>
          <div class="control">
            <%= form.submit t("form.search"), class: "button is-info" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="level-right">
    <div class="level-item">
      <% if !super_admin? && signed_in_admin_user? %>
        <%= link_to t("index.new.ektar/invitation"), "#", class: "button is-primary", data: { action: "modal-view#show" } %>
      <% end %>
    </div>
  </div>
</nav>

app/views/ektar/admin/users/index.html.erb
<div data-controller="modal-view">
  <%= render partial: "tools" %>

  <table class="table is-fullwidth is-hoverable">
    <thead>
      <tr>
        <% list_attributes.each do |attribute| %>
          <th>
            <%= resource_class.human_attribute_name(attribute) %>
          </th>
        <% end %>

        <% if current_user&.super_admin? || signed_in_admin_user? %>
          <th class="has-text-right"><%= t("index.actions.name") %></th>
        <% end %>
      </tr>
    </thead>

    <%= render partial: "resource", collection: collection, as: :resource %>
  </table>

  <h6 class="pagination-info"><%= pagy_info(@pagination) %></h6>
  <%== pagy_bulma_nav(@pagination) if @pagination.pages > 1 %>

  <% if current_user&.super_admin? || signed_in_admin_user? %>
    <div class="modal" data-target="modal-view.modal">
      <div class="modal-background"></div>
      <div class="modal-content">
        <div class="box" data-target="modal-view.content" data-modal-view-url="<%= new_admin_invitation_path %>">
        </div>
      </div>
      <button class="modal-close is-large" aria-label="close" data-action="modal-view#close"></button>
    </div>
  <% end %>
</div>